stages:
  data_ingestion:
    cmd: python -m src.pipeline.run_stage ingest
    deps:
      - src/components/data_ingestion.py

    outs:
      - artifact/data_ingestion/raw
      - artifact/data_ingestion/data_ingested

  data_transformation:
    cmd: python -m src.pipeline.run_stage transform
    deps:
      - src/components/data_transformation.py
      - artifact/data_ingestion/data_ingested

    outs:
      - artifact/data_transformation/transformed

  model_train:
    cmd: python -m src.pipeline.run_stage train
    deps:
      - config/hyperparams.yaml
      - src/components/model_trainer.py
      - artifact/data_transformation/transformed

    outs:
      - artifact/model_trainer/checkpoints
      - artifact/model_trainer/adapter

  model_evaluate:
    cmd: python -m src.pipeline.run_stage evaluate
    deps:
      - src/components/model_evaluation.py
      - artifact/model_trainer/adapter
      - artifact/data_transformation/transformed

    metrics:
      - artifact/model_evaluation/metrics.json:
          cache: false
