lora:
  lora_r: 16
  lora_alpha: 16
  lora_dropout: 0.05
  target_modules:
    - "q_proj"
    - "k_proj"
    - "v_proj"
    - "o_proj"
    - "up_proj"
    - "gate_proj"
    - "down_proj"
  use_rslora: true

model:
  lr: 1e-4
  epochs: 1
  batch_size: 4
  grad_accum: 4
  warmup_ratio: 0.05
  weight_decay: 0.01
  lr_scheduler: "cosine"
  logging_steps: 10
  eval_steps: 1000
  save_steps: 1000
  save_total_limit: 3
